### ISSUE TITLE
MSI B450M MORTAR

### ISSUE THREAD

**Issue by StrictAvacado** [nagisa/msi-rgb#23]
the new msi mortar board uses the nct6797D. Can msi-rgb work with this superio?

**Comment by nagisa** [comment]
Maybe.

**Comment by kingwarrick** [comment]
Testing on an MSI B450M Mortar.
`$ ./msi-rgb -V
msi-rgb 0.1.0`


`$ sudo ./msi-rgb 0 0 0 --print-current
Bank 12 (d0...100): \
ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff\ 
01 08 00 00 00 00 00 00 ff ff 11 00 00 20 01 40\
00 00 00 00 00 00 00 00 00 00 00 00 0e 07 ff 00
Bank 09 (20...40):
d4 51 ff 00 00 00 40 10 00 ff 40 00 01 00 00 01
0f ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
Bank 0b (60...70):
0a 20 0a 30 00 00 ff ff ff ff ff ff ff ff ff ff
error: could not set the colour
    caused by: The sI/O chip identifies as d451, which does not seem to be NCT6795D
    caused by: `--ignore-check` flag, which would skip the check, is not specified (may be dangerous); also try `--base-port``

**Comment by kingwarrick** [comment]
Am willing to help make this happen. I want to disable the on-board LEDs. First issue is:
`sI/O chip identifies as d451`

Let me know how I can further diagnose. `superiotool` does not identify the chip, and I am not sure how else to identify it.

MSI B450M Mortar

$ cat /sys/class/dmi/id/bios_version 
1.10

$ ./msi-rgb -V 
msi-rgb 0.1.0

$ sudo ./msi-rgb 0 0 0 --print-current
Bank 12 (d0...100):
ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
01 08 00 00 00 00 00 00 ff ff 11 00 00 20 01 40
00 00 00 00 00 00 00 00 00 00 00 00 0e 07 ff 00
Bank 09 (20...40):
d4 51 ff 00 00 00 40 10 00 ff 40 00 01 00 00 01
0f ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
Bank 0b (60...70):
0a 20 0a 30 00 00 ff ff ff ff ff ff ff ff ff ff
error: could not set the colour
  caused by: The sI/O chip identifies as d451, which does not seem to be NCT6795D
  caused by: `--ignore-check` flag, which would skip the check, is not specified (may be dangerous); also try `--base-port`

**Comment by nagisa** [comment]
Sadly, looking at the `--print-current` output, it does not appear that the registers are compatible, but you *can* try with `--ignore-check`... but do have in mind the caveat that it might brick your board… Any one of you will just have to bite the bullet ant try it.

**Comment by nagisa** [comment]
You’ll have to manually inspect the board. Tools like `sensors-detect` detect the chip using the mapping from numbers like `d451` to chip models read off the chips directly, the chips do not self-identify any other way.

**Comment by nagisa** [comment]
FWIW, I’ve received a report that B450 TOMAHAWK RGB control works with `--ignore-check`. Its chip identifies with the same `d451`. If somebody can confirm that B450 MORTAR also works, I’m gonna add that identifier to the list of supported identifiers.

**Comment by kingwarrick** [comment]
Have manually loaded nct6775 module in kernel 4.18.0-0.bpo3 (debian) with option force_id=0xd350 to get sensors working.

Confirming that this command to disable RGB works perfectly:
`sudo ./target/release/msi-rgb --disable --ignore-check 00 00 00`

No more lights!
Thank you for your work on this.

**Comment by nagisa** [comment]
Awesome!

**Comment by nagisa** [comment]
The tool should work without `ignore-check` now.
